### ISSUE TITLE
Add tests for cpu v4 instructions

### ISSUE THREAD

**Issue by dthaler** [Alan-Jowett/bpf_conformance#152]
- [X] add BPF_SDIV (signed division) (PR #153)
- [x] add BPF_SMOD (signed modulo) (PR #176)
- [ ] add BPF_MOVSX (sign extension)
- [x] add BPF_ALU64 | BPF_TO_LE (unconditional byteswap) (PR #180)
- add BPF_JA | BPF_JMP32 (32-bit jump) (issue #171)

Documentation references:
* https://github.com/ietf-wg-bpf/ebpf-docs/pull/42 
* https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/Documentation/bpf/standardization/instruction-set.rst?id=245d4c40c09bd8d5a71640950eeb074880925b9a
